# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_creative',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_educational',
        ),
    ]
