# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160526_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likes_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='likes_adventure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='likes_crime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='likes_fan_fiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='likes_fantasy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='likes_horror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='likes_romance',
            field=models.BooleanField(default=False),
        ),
    ]
