# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
