# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0011_post_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_edit', models.TextField()),
                ('language_well', models.TextField()),
                ('language_improve', models.TextField()),
                ('character_well', models.TextField()),
                ('character_improve', models.TextField()),
                ('setting_well', models.TextField()),
                ('setting_improve', models.TextField()),
                ('structure_well', models.TextField()),
                ('structure_improve', models.TextField()),
                ('theme_well', models.TextField()),
                ('theme_improve', models.TextField()),
                ('overall_comment', models.TextField()),
                ('overall_rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
